export const dynamic = 'force-dynamic';

import { getManualDpWorldRankings } from '@/app/lib/dpworld-rankings-store';
import { canonicalNameKey } from '@/app/lib/name-match';

// DP World Tour rankings.
//
// PRIMARY source is the commissioner's pasted list (managed at /commissioner-dpworld, stored in Redis) —
// updatable instantly with no code change or deploy. The map below is the built-in snapshot, used as a
// FALLBACK for any player the pasted list doesn't include (and whenever no list has been pasted yet).
const DP_WORLD_RANKINGS: Record<string, number> = {
  'Patrick Reed': 1,
  'Rory McIlroy': 2,
  'Jayden Schaper': 3,
  'Jayden Trey Schaper': 3,
  'Aaron Rai': 4,
  'Casey Jarvis': 5,
  'Eugenio Chacarra': 6,
  'Andy Sullivan': 7,
  'Dan Bradbury': 8,
  'Shaun Norris': 9,
  'Mikael Lindberg': 10,
  'Daniel Hillier': 11,
  'Bernd Wiesberger': 12,
  'Alex Fitzpatrick': 13,
  'Julien Guerrier': 14,
  'Kota Kaneko': 15,
  'Oliver Lindell': 16,
  'David Puig': 17,
  'Calum Hill': 18,
  'Marcus Armitage': 19,
  'Davis Bryant': 20,
  'Jorge Campillo': 21,
  'Nacho Elvira': 22,
  'Angel Ayora': 23,
  'Jacob Skov Olesen': 24,
  'Jon Rahm': 25,
  'Freddy Schott': 26,
  'Ricardo Gouveia': 27,
  'Hennie Du Plessis': 28,
  'Adrian Otaegui': 29,
  'Justin Rose': 30,
  'Tyrrell Hatton': 31,
  'Kristoffer Reitan': 32,
  'Richard Sterne': 33,
  'Jordan Gumberg': 34,
  'Wenyi Ding': 35,
  'Yurav Premlall': 36,
  'Ludvig Aberg': 37,
  'Ludvig Åberg': 37,
  'Nathan Kimsey': 38,
  'Daniel Rodrigues': 39,
  'Justin Thomas': 40,
  'Rasmus Neergaard-Petersen': 41,
  'Ewen Ferguson': 42,
  'Martin Couvra': 43,
  'Francesco Molinari': 44,
  'Darius Van Driel': 45,
  'Gregorio De Leo': 46,
  'Rafa Cabrera Bello': 47,
  'Ugo Coussaud': 48,
  'Francesco Laporta': 49,
  'Alejandro Del Rey': 50,
  'JC Ritchie': 51,
  'Guido Migliozzi': 52,
  'Frederic Lacroix': 53,
  'Antoine Rozner': 54,
  'John Parry': 55,
  'Ryan Gerard': 56,
  'Brandon Robinson Thompson': 57,
  'Nicolai Hojgaard': 58,
  'Nicolai Højgaard': 58,
  'Eddie Pepperell': 59,
  'Oihan Guillamoundeguy': 60,
  'David Ravetto': 61,
  'Maximilian Steinlechner': 62,
  'Johannes Veerman': 63,
  'Tom Vaillant': 64,
  'Joe Dean': 65,
  'Matt Fitzpatrick': 66,
  'Matthew Fitzpatrick': 66,
  'Shane Lowry': 67,
  'Grant Forrest': 68,
  'Sebastian Soderberg': 69,
  'Sebastian Söderberg': 69,
  'Michael Hollick': 70,
  'Yanhan Zhou': 71,
  'Daniel Van Tonder': 72,
  'Zander Lombard': 73,
  'Manuel Elvira': 74,
  'Marcus Kinhult': 75,
  'Chris Gotterup': 76,
  'Dylan Frittelli': 77,
  'Kazuma Kobori': 78,
  'Christiaan Bezuidenhout': 79,
  'Tommy Fleetwood': 80,
  'Adam Scott': 81,
  'Si Woo Kim': 82,
  'Ryan Fox': 83,
  'Thriston Lawrence': 84,
  'Joost Luiten': 85,
  'Andreas Halvorsen': 86,
  'Jason Scrivener': 87,
  'Angel Hidalgo': 88,
  'Angel Hidalgo Portillo': 88,
  'Viktor Hovland': 89,
  'Jacques Kruyswijk': 90,
  'Min Woo Lee': 91,
  'Matthew Jordan': 92,
  'Kiradech Aphibarnrat': 93,
  'Thorbjorn Olesen': 94,
  'Thorbjørn Olesen': 94,
  'Matteo Manassero': 95,
  'Marcel Schneider': 96,
  'Romain Langasque': 97,
  'Rikuya Hoshino': 98,
  'Joakim Lagergren': 99,
  'Yuto Katsuragawa': 100,
  'Alexander Levy': 101,
  'Thomas Detry': 102,
  'David Law': 103,
  'Hugo Townsend': 104,
  'Brandon Stone': 105,
  'Anthony Quayle': 106,
  'Cameron Adam': 107,
  'Euan Walker': 108,
  'Niklas Norgaard': 109,
  'Niklas Nørgaard': 109,
  'Niklas Norgaard Moller': 109,
  'Niklas Nørgaard Møller': 109,
  'Victor Perez': 110,
  'Haotong Li': 111,
  'Sam Bairstow': 112,
  'Tobias Jonsson': 113,
  'James Morrison': 114,
  'Andrea Pavan': 115,
  'Joel Girrbach': 116,
  'Ben Schmidt': 117,
  'Ivan Cantero': 118,
  'Sebastian Garcia': 119,
  'Marcel Siem': 120,
  'Jeff Winther': 121,
  'Todd Clements': 122,
  'Matt Wallace': 123,
  'Sean Crocker': 124,
  'Andrew Johnston': 125,
  'Alex Noren': 126,
  'Jonathan Broomhead': 127,
  'Jens Dantorp': 128,
  'Paul Waring': 129,
  'Ross Fisher': 130,
  'Tom McKibbin': 131,
  'Jack Senior': 132,
  'Daniel Young': 133,
  'Padraig Harrington': 134,
  'Scott Jamieson': 135,
  'Ashun Wu': 136,
  'Stefano Mazzoli': 137,
  'David Micheluzzi': 138,
  'Ryan Peake': 139,
  'Quim Vidal': 140,
  'Junghwan Lee': 141,
  'Elvis Smylie': 142,
  'Matthew Baldwin': 143,
  'Rocco Repetto Taylor': 144,
  'Rocco Paolo Repetto Taylor': 144,
  'Niklas Lemke': 145,
  'Ryggs Johnston': 146,
  'Nicolai Von Dellingshausen': 147,
  'Richie Ramsay': 148,
  'Danny Willett': 149,
  'Sepp Straka': 150,
  'Clement Charmasson': 151,
  'Aaron Cockerill': 152,
  'Sungjae Im': 153,
  'Laurie Canter': 154,
  'Tapio Pulkkanen': 155,
  'Michael Kim': 156,
  'Renato Paratore': 157,
  'Marco Penge': 158,
  'Quentin Debove': 159,
  'Ockie Strydom': 160,
  'Sami Valimaki': 161,
  'Sami Välimäki': 161,
  'Benjamin Follett-Smith': 162,
  'Sadom Kaewkanjana': 163,
  'Jack Buchanan': 164,
  'Robin Williams': 165,
  'Dylan Naidoo': 166,
  'Albin Bergstrom': 167,
  'Fabrizio Zanotti': 168,
  'Connor Syme': 169,
  'Adri Arnaus': 170,
  'Shubhankar Sharma': 171,
  'Zac Blair': 172,
  'Filippo Celli': 173,
  'Joshua Berry': 174,
  'Jesper Svensson': 175,
  'Pablo Larrazabal': 176,
  'Pablo Larrazábal': 176,
  'Robert MacIntyre': 177,
  'Alfredo Garcia-Heredia': 178,
  'Rasmus Hojgaard': 179,
  'Rasmus Højgaard': 179,
  'Frederico Biondi Figueiredo': 180,
  'Ryan Van Velzen': 181,
  'Lucas Bjerregaard': 182,
  'Felix Mory': 183,
  'Will Zalatoris': 184,
  'Taehoon Ok': 185,
  'Yuvraj Sandhu': 186,
  'Connor McKinney': 187,
  'Harry Higgs': 188,
  'Adrien Saddier': 189,
  'Marcus Helligkilde': 190,
  'Daniel Brown': 191,
  'Jordan Smith': 192,
  'Jovan Rebula': 193,
  'Callum Tarren': 194,
  'Adrian Meronk': 195,
  'Mike Toorop': 196,
  'Richard Mansell': 197,
  'Jamie Rutherford': 198,
  'Daniel Gavins': 199,
  'Yannik Paul': 200,
  'Jeong Weon Ko': 201,
  'Clement Sordet': 202,
  'Darren Fichardt': 203,
  'Hunter Logan': 204,
  'Edoardo Molinari': 205,
  'Andres German Gallegos': 206,
  'Luke Donald': 207,
  'Dylan Wu': 207,
  'Veer Ahlawat': 209,
  'Deon Germishuys': 210,
  'Simon Forsstrom': 211,
  'Jack Yule': 213,
  'Gavin Green': 214,
};

function normalize(name: string): string {
  return name.trim().toLowerCase()
    .replace(/å/g, 'a').replace(/ä/g, 'a').replace(/ö/g, 'o').replace(/ø/g, 'o')
    .replace(/é/g, 'e').replace(/è/g, 'e').replace(/ë/g, 'e')
    .replace(/ü/g, 'u').replace(/ú/g, 'u')
    .replace(/ñ/g, 'n').replace(/ç/g, 'c')
    .replace(/í/g, 'i').replace(/á/g, 'a');
}

const NORMALIZED_RANKINGS: Map<string, number> = new Map(
  Object.entries(DP_WORLD_RANKINGS).map(([k, v]) => [normalize(k), v])
);

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const name = searchParams.get('name') ?? '';
  if (!name) return Response.json({ rank: null });

  const key = normalize(name);
  const canonKey = canonicalNameKey(name); // order-independent: matches "Last, First" or "First Last"

  // Commissioner's uploaded list wins when present; fall back to the built-in snapshot per player.
  let manualRank: number | null = null;
  try {
    const manual = await getManualDpWorldRankings();
    if (manual) {
      const entries = Object.entries(manual.map);
      // Exact (same order) match first, then an order-independent canonical match so the uploaded
      // names resolve whether they're "Rory McIlroy" or "MCILROY, Rory".
      const exact = entries.find(([rawName]) => normalize(rawName) === key);
      const canon = exact ?? entries.find(([rawName]) => canonicalNameKey(rawName) === canonKey);
      if (canon) manualRank = canon[1];
    }
  } catch { /* fall back to built-in */ }

  const rank = manualRank ?? NORMALIZED_RANKINGS.get(key) ?? null;
  return Response.json({ rank });
}
